### ISSUE TITLE
Dragons spawn in the Twilight Forest

### ISSUE THREAD

**Issue by ArgentailGlacies** [DestroOmega/WandsAndWrenches#17]
They shouldn't, preferably

**Comment by DestroOmega** [comment]
Def shouldn't, totes.

**Comment by DestroOmega** [comment]
Corrected with #aa4d4baf53f8888991720ce7b63bd6e2dcdafb7c
[aa4d4baf53f8888991720ce7b63bd6e2dcdafb7c](url)
