### ISSUE TITLE
.name

### ISSUE THREAD

**Issue by ArgentailGlacies** [DestroOmega/WandsAndWrenches#23]
![image](https://user-images.githubusercontent.com/35341006/214947053-92c0603e-0247-46cd-97fc-6e6ed4027e98.png)

Wat

**Comment by DestroOmega** [comment]
Okay, I'll admit; I have no idea what the center item is.

**Comment by DestroOmega** [comment]
Wait, found it. Crane magnet from openblocks. I'm going to blame openblocks on this one. Create a clear for it in zenscripts for craftweaker, mayhap?
