### ISSUE TITLE
Recept for changing color of the dragon eggs

### ISSUE THREAD

**Issue by chrrooster** [DestroOmega/WandsAndWrenches#44]
For example green egg + ink = gray dragon egg

**Comment by chrrooster** [comment]
Blerg, the dragon population is increasing way to much, please add ways to make gray dragon eggs from existing fire dragon eggs. Population will increase until the RNG god has blessed me with a grey egg

**Comment by DestroOmega** [comment]
You were admin-haxored in an egg by Hep. Closed.
