### ISSUE TITLE
AE2 and IC2 crafting incompatibility

### ISSUE THREAD

**Issue by ArgentailGlacies** [DestroOmega/WandsAndWrenches#46]
Whenever components containing batteries, energy storage, or similar items from Industrialcraft 2 are crafted using Applied Energistics, the crafting halts and hangs. This issue makes it super-tedious to automate the crafting of many items from IC2 using AE2. A possible solution is to write a script that re-creates the IC2 recipes using vanilla crafting recipes, rather than whatever the crap IC2 does.

**Comment by DestroOmega** [comment]
Solution: Automate IC2 crafting using IC2.

**Comment by ArgentailGlacies** [comment]
*Sad crafting table noises*
